version: 2
jobs:
  run_unit_tests_with_jacoco_coverage_with_coveralls:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: "Run unit tests"
          command: gradle cleanTest test jacocoTestReport coveralls
          # to be able to upload to coveralls make sure to add COVERALLS_REPO_TOKEN Environment Variable

      - store_artifacts:
          path: build/spock-reports

      - store_artifacts:
          path: build/test-results/test
      - store_test_results:
          path: build/test-results/test

workflows:
  version: 2
  execute_unit_tests:
    jobs:
      - run_unit_tests_with_jacoco_coverage_with_coveralls